---
# Created for and tested on Ubuntu Server 24.04
# Run after completing the 'prep new node' playbook
# Run cmd: ansible-playbook kb2_install_kubernetes.yml -K --extra-vars "selected_hosts=<pattern>"
- name: "Kubernetes: Install core packages (all nodes)"
  hosts: "{{ selected_hosts }}"
  become: True
  become_method: sudo
  
  ##### TASKS #####
  tasks:

  - name: "Preflight: Run 'apt update'"
    debug:
      msg: "Resynchronizing apt package indexes."
    notify: "Run apt update"

  # Flush to execute any notified handlers now
  - name: FLush handlers
    meta: flush_handlers

  # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/     
  - name: "Package: Install - kubernetes prerequisites"
    ansible.builtin.apt:
      name: "{{ item  }}"
      state: latest
      install_recommends: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg

  - name: "Shell: Install kubernetes gpg key"
    ansible.builtin.shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: "Shell: Install kubernetes repositories"
    ansible.builtin.shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
    notify: "Run apt update"

  # Flush to execute any notified handlers now
  - name: FLush handlers
    meta: flush_handlers

  - name: "Package: Install - kubernetes core binaries"
    ansible.builtin.apt:
      name: "{{  item }}"
      state: latest
    loop:
      - kubelet
      - kubeadm
      - kubectl


  ##### HANDLERS #####
  handlers:

  - name: "Run apt update"
    ansible.builtin.apt:
      update_cache: yes 

